config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "flats#index"

  resources :users

  resources :flats do
    resources :reservations
  end

  resources :reservations, only: [:new, :create, :destroy, :show, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_one_attached :image
  # validate :address, :price, :size, :room
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  # validate :user_id, :flat_id
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :flats, :reservations
  has_many :flats
  has_many :reservations

  # validate :first_name, :last_name, :email, :phone_number, :address, presence: true
  # validate :email, :phone_number, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

 def new
    @flat = Flat.new
 end

 def index
    @pages = Flat.all
 end

 def show
   @user = current_user
   @flat = Flat.find(params[:id])
 end

 def create
  if current_user
   @flat = Flat.new(flat_params)
   @flat.user = current_user
   if @flat.save
     redirect_to flat_path(@flat)
   else
     render :new, status: :unprocessable_entity
   end
  end
 end

 def edit
   @flat = Flat.find(params[:id])
 end

 def update
   @flat = Flat.find(params[:id])
  if @flat.update(flat_params)
    redirect_to @flat, notice: 'Flat was successfully updated.'
  else
    render :edit
  end
 end

 def destroy
   @flat = Flat.find(params[:id])
   @flat.destroy
   redirect_to flats_path
 end

 private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price, :room, :category, :country, :city)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

    def index
  if user_signed_in?
     @user_reservations = current_user.reservations
  else
    redirect_to new_user_session_path, alert: 'Veuillez vous connecter pour voir vos réservations.'
  end
  end


    def new
    @flat = Flat.find(params[:flat_id])
    @reservation = Reservation.new
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @reservation = @flat.reservations.build(reservation_params)
    @reservation.user = current_user
    @reservation.status = 'En attente de validation'

    if verif && @reservation.save
      redirect_to flat_reservation_path(@flat, @reservation), notice: 'Réservation créée avec succès!'
    else
      redirect_to flat_path(@flat), notice: 'Réservation impossible sur ces dates.'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @reservation = Reservation.new
  end


  private

  def reservation_params
    params.require(:reservation).permit(:start_reservation, :end_reservation, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    

    def new
        @user = User.new
    end

    def show
        @user = current_user
        @flats = Flat.where(user: current_user)
        @reservations = Reservation.where(flat_id: @flat.pluck(:id))
        @resers = Reservation.where(user: current_user)
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to users_path, notice: 'Utilisateur créé avec succès!'
        else
            render :new
        end
    end

    def reservations
        @user = User.find(params[:user_id])
        @reservations = @user.reservations
    end

    def all_reservations
        puts "Entering all_reservations action"
        @user = current_user
        @reservations = @user.reservations
  puts "Number of reservations: #{ @reservations.count }"
    end


    private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/index.html.erb
<div class="index-pages-container body-color">
  <div class="index-container">
    <% @pages.each do |flat| %>
      <div class="cards">
        <% if flat.present? %>
          <%= link_to flat_path(flat), class: "card-link" do %>
            <div class="card-body">
              <div class="flat-image">
                <img src="https://www.vacationkey.com/photos/5/3/53968-5.jpg">
              </div>
              <h4 class="cutlink"><%= flat.name %></h4>
              <p><%= flat.description %></p>
              <p><%= flat.address %></p>
              <p><%= flat.price %>€/jour</p>
            </div>
          <% end %>
        <% else %>
          <p>Aucun appartement disponible</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="form-flat">
    <%= simple_form_for(@flat) do |f| %>
        <div class="form-group">
            <%= f.label :name, class: "form-label" %>
            <%= f.text_field :name, class: "form-control", placeholder: "Title:" %>
        </div>

        <div class="form-group">
            <%= f.label :price, class: "form-label" %>
            <%= f.number_field :price, class: "form-control", placeholder: "Price:" %>
        </div>

        <div class="form-group">
            <%= f.label :city, class: "form-label" %>
            <%= f.text_field :city, class: "form-control", placeholder: "City:" %>
        </div>

        <div class="form-group">
            <%= f.label :country, class: "form-label" %>
            <%= f.text_field :country, class: "form-control", placeholder: "Country:" %>
        </div>

        <div class="form-group">
            <%= f.label :address, class: "form-label" %>
            <%= f.text_field :address, class: "form-control", placeholder: "Address:" %>
        </div>

        <div class="form-group">
            <%= f.label :description, class: "form-label" %>
            <%= f.text_area :description, class: "form-control", placeholder: "Description:" %>
        </div>

        <div class="form-group">
            <%= f.label :room, class: "form-label" %>
            <%= f.text_field :room, class: "form-control", placeholder: "Room:" %>
        </div>

        <div class="form-group">
            <%= f.label :category, class: "form-label" %>
            <%= f.text_field :category, class: "form-control", placeholder: "Category:" %>
        </div>

        <%= f.submit "Ajouter votre logement", class: "btn-submit" %>
    <% end %>
</div>

app/views/flats/show.html.erb
<div class="flat-page">
  <div class="flat-header">
    <h1><%= @flat.name %></h1>
    <div class="flat-image">
      <img src="https://www.vacationkey.com/photos/5/3/53968-5.jpg">
    </div>
    <p class="flat-category">Catégorie : <%= @flat.category %></p>
    <p class="flat-address">Adresse : <%= @flat.address %>, <% @flat.city %> <% @flat.country %></p>
  </div>
  <div class="flat-body">
    <p class="flat-description">Description : <%= @flat.description %></p>
    <p class="flat-rooms">Nombre de pièces : <%= @flat.room %></p>
    <p class="flat-price">Prix : <%= @flat.price %> € par nuit</p>

    <% if current_user == @flat.user %>
  <div class="p-2 text-center">
    <%= button_to "Delete", flat_path(@flat), method: :delete, class: "btn btn-outline-success" %>
    <%= button_to "Edit", edit_flat_path(@flat), method: :get, class: "btn btn-outline-info" %>
    <%= button_to "Update", flat_path(@flat), method: :patch %>
  </div>
<% else %>
  <%= link_to 'Réserver cet appartement', new_flat_reservation_path(@flat), class: 'btn btn-primary' %>
<% end %>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestCerfif</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<h1>Mes Réservations</h1>
<div class="reservation-list">
  <% if @user_reservations&.any? %>
    <% @user_reservations.each do |reservation| %>
  <div class="reservation-item">
    <% if reservation.flat.image.attached? %>
      <%= image_tag url_for(reservation.flat.image), alt: reservation.flat.name, class: "reservation-image" %>
    <% else %>
      <%= image_tag("https://a0.muscache.com/im/pictures/miso/Hosting-992604588463714327/original/581bd53c-d4fd-4214-bbd2-8b61e33c020b.jpeg", alt: reservation.flat.name, class: "reservation-image") %>
    <% end %>
    <div class="reservation-details">
      <strong><%= reservation.flat.name %></strong><br>
      <strong>Date de début:</strong> <%= reservation.start_of_reservation %><br>
      <strong>Date de fin:</strong> <%= reservation.end_of_reservation %><br>
      <%= link_to "Supprimer ma réservation", reservation_path(reservation), data: { turbo_method: :delete, turbo_confirm: "Es-tu sûr?" }, class: "btn btn-danger" %>
    </div>
  </div>
<% end %>

  <% else %>
    <p>Vous n'avez aucune réservation pour le moment.</p>
  <% end %>
</div>

app/views/reservations/new.html.erb
<div class="form-container card-color">
  <h2>A quelle date voulez-vous réserver ce bien?</h2>
  <p><%= @flat.name %></p> <br>
  <%= form_with(model: [@flat, @reservation], local: true) do |form| %>
    <div class="field">
      <%= form.label :start_reservation %>
      <%= form.date_field :start_reservation %>
    </div>
    <div class="field">
      <%= form.label :end_reservation %>
      <%= form.date_field :end_reservation %>
    </div>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="actions">
      <%= link_to 'Réserver',  flat_reservations_path(@flat), class: 'btn btn-secondary', method: :post %>
    </div>
  <% end %>
  <%= link_to 'Retour à la liste des logements', flats_path, class: 'btn btn-secondary' %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Louer votre appartement", new_flat_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>